config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :users
  resources :brands do
    resources :locations
  end

  get   'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :brands

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:show, :edit, :update, :destroy] # Restrict viewing, editing, and destroying other users
  skip_before_action :require_user, only: [:new, :create, :edit] # Restrict everything but new, create, edit
  skip_before_action :require_admin, only: [:show, :new, :create, :edit, :update] # Restrict everything but, show, new, create, edit, update

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "Successfully updated user!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully removed user!"
      @user.destroy
      redirect_to users_path
    else
      flash[:notice] = "There was an error, insufficient permissions."
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= render 'shared/error_messages' %>

<%= form_for(@user) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/_form_new.html.erb
<%= render 'shared/error_messages' %>

<%= form_for(@user) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'form-control input-lg' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, :class => 'form-control input-lg' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :class => 'form-control input-lg' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation, :class => 'form-control input-lg' %>
  </div>

  <div class="form-group">
    <%= f.submit :class => 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/users/_form_update.html.erb
<%= render 'shared/error_messages' %>

<%= form_for(@user) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'form-control input-lg' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, :class => 'form-control input-lg' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :class => 'form-control input-lg' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => 'form-control input-lg' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% content_for :header do %>
  <h1><%=t :edit %> <%= @user.name %></h1>
<% end %>
<%= render 'form_update' %>

app/views/users/index.html.erb
<% content_for :header do %>
  <h1><%=t :users %></h1>
<% end %>

<% @users.each do |user| %>
  <div class="profile">
    <%=t :name%> : <%= user.name %> <%= gravatar_for user %> <br>
    <%=t :email %> : <%= user.email %> <br>
    <%=t :admin %> : <%= user.admin? %> <br>
  </div>

  <%= render partial: 'shared/actions', locals: { collection: user, name: 'User', path: edit_user_path(user) } %>
  <hr>
<% end %>

app/views/users/new.html.erb
<% content_for :header do %>
  <h1><%=t 'create_new' %></h1>
<% end %>
<div class="row">
  <div class="col-md-5">
    <%= render 'form_new' %>
    <p><%=t 'have_account' %> <%= link_to "Sign in", sessions_new_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :header do %>
<h1><%= @user.name %></h1>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="profile">
      <%=t :name %> : <%= @user.name %> <%= gravatar_for @user %> <br>
      <%=t :email %> : <%= @user.email %> <br>
      <%=t :admin %> : <%= @user.admin? %> <br>
    </div>
  </div>
</div>

<%= render partial: 'shared/actions', locals: { collection: @user, name: 'User', path: edit_user_path(@user) } %>