config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :users
  resources :brands do
    resources :locations
  end

  get   'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_actions.html.erb
<div class="btn-group" role="group" aria-label="Edit User">
  <div class="btn-group">
    <%= link_to collection, :class => "btn btn-primary" do %>
    <i class="fa fa-eye fa-fw fa-lg" aria-hidden="true"></i>
    <% end %>

    <%= link_to path, :class => "btn btn-success" do %>
    <i class="fa fa-cog fa-fw fa-lg" aria-hidden="true"></i>
    <% end %>

    <%= link_to collection, method: :delete, data: { confirm: "Are you sure you wish to delete?" }, :class => "btn btn-danger" do %>
    <i class="fa fa-trash fa-fw fa-lg" aria-hidden="true"></i>
    <% end %>
  </div>
</div>

app/views/shared/_breadcrumb.html.erb
<div class="row">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li><%= link_to name, link %></li>
      <li class="active"><%= collection.name %></li>
    </ol>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
The form contains <%= pluralize(@user.errors.count, "error") %>.

<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

app/views/shared/_footer.html.erb
<% if !yield(:footer).empty? %>
  <%= yield :footer %>
<% end %>

app/views/shared/_header.html.erb
<% if !yield(:header).empty? %>
<section class="header">
  <div class="header-bg">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= yield :header %>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

app/views/shared/_primary_navigation.html.erb
<nav class="navbar navbar-default brand-nav">
  <div class="container">

    <% if yield(:brand_logo).empty? %>
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">
        <%= image_tag 'brand-smswmedia.png', :class => 'brand-logo' %>
      </a>
    </div>
    <% else %>
    <%= yield(:brand_logo) %>
    <% end %>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="locale-ar"><%= link_to 'English', url_for( :locale => 'en' ), method: :get %></li>
        <li class="locale-en"><%= link_to 'Arabic', url_for( :locale => 'ar' ), method: :get %></li>
        <% if logged_in? %>
        <li>
          <div class="avatar small"><%= gravatar_for current_user %></div>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to(t('home'), root_path) %></li>
            <li><%= link_to(t('profile'), user_path(current_user)) %></li>
            <li><%= link_to(t('brands'), brands_path) %></li>
            <li><%= link_to(t('users'), users_path) %></li>
            <li><%= link_to(t('sign_out'), logout_path, method: :delete) %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>