config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :users
  resources :brands do
    resources :locations
  end

  get   'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  include Obfuscate

  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :description, presence: true
  validates :logo, presence: true
  validates :url, presence: true

  belongs_to :user
  has_many :locations, dependent: :destroy

  def to_param
    encrypt id
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  skip_before_action :require_user, only: [:show]
  skip_before_action :require_admin, only: [:show]
  before_action :set_brand, only: [:show, :edit, :update, :destroy]
  before_action :set_region, only: [:show]

  def index
    @brands = Brand.all
  end

  def create
    @brand = current_user.brands.new(brand_params)
    if @brand.save
      flash[:notice] = "Brand successfully created!"
      redirect_to @brand
    else
      render 'new'
    end
  end

  def update
    if @brand.update_attributes(brand_params)
      flash[:notice] = "Brand successfully updated!"
      redirect_to @brand
    else
      render 'edit'
    end
  end

  def destroy
    if @brand.destroy
      flash[:notice] = "Brand successfully removed!"
      @brand.destroy
      redirect_to brands_path
    end
  end

  def show
  end

  def new
    @brand = Brand.new
  end

  def edit
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_brand
    @brand = Brand.find Brand.decrypt(params[:id])
  end

  def set_region
    region = []
    locations = @brand.locations
    locations.each do |location|
      region.push(location.region)
    end
    @regions = region.uniq
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def brand_params
    params.require(:brand).permit(:title, :logo, :url, :description, :published)
  end
end

app/views/brands/_brand_logo.html.erb
<% content_for :brand_logo do %>
<div class="navbar-header">
  <a class="navbar-brand" href="#">
    <img alt="Brand" src='<%= @brand.logo %>' style="width: 120px;">
  </a>
</div>
<% end %>

app/views/brands/_details.html.erb
<p>
  <strong><%=t :title %> :</strong>
  <%= @brand.title %>
</p>

<p>
  <strong><%=t :logo %> :</strong>
  <%= @brand.logo %>
</p>

<p>
  <strong><%=t :url %> :</strong>
  <%= @brand.url %>
</p>

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
<% if @brand.errors.any? %>
<div>
  <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>
  <ul>
    <% @brand.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, :class => "form-control input-lg" %>
</div>

<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, :class => "form-control input-lg" %>
</div>

<div class="form-group">
  <%= f.label :logo %>
  <%= f.text_field :logo, :class => "form-control input-lg" %>
</div>

<div class="form-group">
  <%= f.label :url %>
  <%= f.text_field :url, :class => "form-control input-lg" %>
</div>

<div class="checkbox">
  <label>
    <%= f.check_box :published %> <%=t :published %>?
  </label>
</div>

<div class="form-group">
  <%= f.submit :class => 'btn btn-primary btn-lg' %>
</div>
<% end %>

app/views/brands/_google_map.html.erb
<div class="embed-responsive embed-map">
  <div id="map" class="embed-responsive-item">
  </div>
</div>

<% content_for :footer_third_party do %>
  <script src="//maps.googleapis.com/maps/api/js?key=AIzaSyDkiHUkl-Syk3ZkNZYQcmLQZW3mNQZYj-Y&region=AR&v=3.23&callback=initMap" async defer></script>
<% end %>

app/views/brands/_map_filters.html.erb
<div class="form-group locale-en">
  <label for="region" class="control-label sr-only"><%=t :select_region %></label>
  <select id="region" onchange="filterResult(this.value);" class="form-control">
    <option value="all"><%=t :select_region %></option>
    <% @regions.each do |region| %>
      <option value="<%= region['region_en'] %>"><%= region['region_en'] %></option>
    <% end %>
  </select>
</div>

<div class="form-group locale-ar">
  <label for="region" class="control-label sr-only"><%=t :select_region %></label>
  <select id="region" onchange="filterResult(this.value);" class="form-control">
    <option value="all"><%=t :select_region %></option>
    <% @regions.each do |region| %>
      <option value="<%= region['region_ar'] %>"><%= region['region_ar'] %></option>
    <% end %>
  </select>
</div>

app/views/brands/edit.html.erb
<%= render partial: 'brands/brand_logo' %>
<h1><%=t :edit %> <%=t :brand %></h1>
<%= render 'form' %>

app/views/brands/index.html.erb
<% content_for :header do %>
  <h1><%=t :brands %></h1>
<% end %>

<div class="row">
  <div class="col-md-12">
    <h2><%=t :landmark_group %>
      <small><%= link_to(t('create_new'),  new_brand_path, :class => 'btn' )%></small>
    </h2>
  </div>

  <% @brands.each do |brand| %>
  <div class="col-md-3">
    <div class="brand-info-box <%= brand_class %>">

      <div class="brand-logo">
        <img src="<%= brand.logo %>">
      </div>

      <div class="brand-details">
        <h4><%=t :brand %> : <%= brand.title %></h4>
        <p><%=t :description %> : <%= brand.description %></p>
        <p><%=t :online %>: <%= brand.published? %></p>
      </div>

      <div class="btn-group" role="group" aria-label="Edit Brands">
        <div class="btn-group">
          <%= link_to brand, :class => "btn btn-primary" do %>
          <i class="fa fa-eye fa-fw fa-lg" aria-hidden="true"></i>
          <% end %>

          <%= link_to edit_brand_path(brand), :class => "btn btn-success" do %>
          <i class="fa fa-cog fa-fw fa-lg" aria-hidden="true"></i>
          <% end %>

          <%= link_to brand, method: :delete, data: { confirm: "Are you sure you wish to delete?" }, :class => "btn btn-danger" do %>
          <i class="fa fa-trash fa-fw fa-lg" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/brands/new.html.erb
<% content_for :header do %>
<h1><%=t :new %> <%=t :brand %></h1>
<% end %>
<%= render 'form' %>

app/views/brands/show.html.erb
<%= render partial: 'brands/brand_logo' %>
<div class="row">

  <div class="col-md-3 map-results hidden">

    <div class="map-filters hidden">
      <input id="searchTextField" type="text" class="form-control" placeholder="<%=t :search %>">
    </div>

    <div class="map-filters">
      <%= render partial: 'map_filters' %>
    </div>

    <div class="map-locations">
      <%= render partial: @brand.locations, collection: @brand.locations %>
    </div>

    <% if is_admin? %>
      <%= link_to new_brand_location_path(@brand), class: 'btn btn-dark' do %>
        <%=t :create_new %> <i class="fa fa-map-marker fa-fw fa-lg" aria-hidden="true"></i>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-9">
    <%= render partial: 'brands/google_map' %>
  </div>
</div>

<% content_for :footer do %>
<%= javascript_include_tag '//maps.googleapis.com/maps/api/js?key=AIzaSyDkiHUkl-Syk3ZkNZYQcmLQZW3mNQZYj-Y&libraries=places&callback=initMap' %>
<% end %>