config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :users
  resources :brands do
    resources :locations
  end

  get   'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates :name_en, presence: true
  validates :name_ar, presence: true
  validates :region_en, presence: true
  validates :region_ar, presence: true
  validates :opening_hours, presence: true
  validates :content_en, presence: true
  validates :content_ar, presence: true
  validates :lat, presence: true
  validates :lng, presence: true

  store_accessor :name, [:name_en, :name_ar]
  store_accessor :region, [:region_en, :region_ar]
  store_accessor :opening_hours, [:mon, :tue, :wed, :thu, :fri, :sat, :sun]
  store_accessor :categories, [:cat_mens, :cat_womens, :cat_kids]
  store_accessor :content, [:content_en, :content_ar]
  belongs_to :brand
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  skip_before_action :require_user, only: [:index, :show]
  skip_before_action :require_admin, only: [:index, :show]
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :set_brand

  def index
    @locations = @brand.locations.all
    render json: @locations
  end

  def create
    @location = @brand.locations.new(location_params)

    if @location.save
      redirect_to @brand
    else
      render 'new'
    end
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(location_params)
      redirect_to @brand
    else
      render 'edit'
    end
  end

  def destroy
    @location = @brand.locations.find(params[:id])
    if @location.destroy
      @location.destroy
      redirect_to @brand
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def edit
    @location = Location.find(params[:id])
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_brand
    @brand = Brand.find Brand.decrypt(params[:brand_id])
  end

  def set_location
    @location = Location.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def location_params
    params[:location].permit([
      :name_en, :name_ar, :content_en, :content_ar, :region_en, :region_ar,
      :mon, :tue, :wed, :thu, :fri, :sat, :sun, :lat, :lng,
      :cat_mens, :cat_womens, :cat_kids
    ])
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_actions.html.erb
<div class="btn-actions btn-group" role="group" aria-label="Edit User">
  <div class="btn-group">
    <button class="btn btn-dark" onclick="openInfoWindow(<%= counter %>);">
      <%=t :find %> <i class="fa fa-location-arrow fa-fw fa-lg" aria-hidden="true"></i>
    </button>
    <% if is_admin? %>
    <%= link_to edit_brand_location_path(@brand, location.id), :class => "btn btn-success" do %>
      <i class="fa fa-cog fa-fw fa-lg" aria-hidden="true"></i>
    <% end %>
    <%= link_to brand_location_path(@brand, location.id), method: :delete, data: { confirm: "Are you sure you wish to delete?" }, :class => "btn btn-danger" do %>
      <i class="fa fa-trash fa-fw fa-lg" aria-hidden="true"></i>
    <% end %>
    <% end %>
  </div>
</div>

app/views/locations/_form.html.erb
<% if logged_in? %>
  <%= form_for [@brand, @location] do |f| %>
  <div class="form-group">

    <!-- Nav tabs -->
    <ul id="new_location_tabs" class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#name_en" aria-controls="name_en" role="tab" data-toggle="tab">English</a></li>
      <li role="presentation"><a href="#name_ar" aria-controls="name_ar" role="tab" data-toggle="tab">Arabic</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="name_en">
        <div class="well">
          <div class="form-group">
            <%= f.label :name_en %>
            <%= f.text_field :name_en , id: "geo_name_en", class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :region_en %><br>
            <%= f.text_field :region_en, id: "geo_region_en", class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :content_en %><br>
            <%= f.text_area :content_en, id: "geo_content_en", class: "form-control" %>
          </div>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane fade" id="name_ar">
        <div class="well">
          <div class="form-group">
            <%= f.label :name_ar %>
            <%= f.text_field :name_ar , id: "geo_name_ar", class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :region_ar %><br>
            <%= f.text_field :region_ar, id: "geo_region_ar", class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :content_ar %><br>
            <%= f.text_area :content_ar, id: "geo_content_ar", class: "form-control" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <h4>Opening Hours</h4>
  <p>Enter opening times, e.g 09:00 - 18:00</p>
  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :mon %>
      <%= f.text_field :mon, class: "form-control" %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :tue %>
      <%= f.text_field :tue, class: "form-control" %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :wed %>
      <%= f.text_field :wed, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-3">
      <%= f.label :thu %>
      <%= f.text_field :thu, class: "form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :fri %>
      <%= f.text_field :fri, class: "form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :sat %>
      <%= f.text_field :sat, class: "form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :sun %>
      <%= f.text_field :sun, class: "form-control" %>
    </div>
  </div>

  <h4>Select a category</h4>
  <p>Choose one ore more categories that are relevent to this location.</p>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :cat_mens, 'Mens' %>
      <%= f.check_box :cat_mens %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :cat_womens, 'Womens' %>
      <%= f.check_box :cat_womens %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :cat_kids, 'Kids' %>
      <%= f.check_box :cat_kids %>
    </div>
  </div>

  <h4>Location data</h4>
  <p>Enter this manually or have the geocoder on the right fill this in for you.</p>
  <div class="row">
    <div class="form-group col-md-6">
      <%= f.label :lat %><br>
      <%= f.text_field :lat, id: "geo_lat", class: "form-control" %>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :lng %><br>
      <%= f.text_field :lng, id: "geo_lng", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary btn-lg" %>
  </div>
  <% end %>
  <% end %>

app/views/locations/_google_map_geocode.html.erb
<h2><%=t :find_by_address %></h2>

<div class="form-group">
  <input id="address" type="textbox" class="form-control" placeholder="<%=t :enter_address %>">
</div>
<div class="form-group">
  <input type="button" class="btn btn-success" value="Geocode address" onclick="codeAddress()">
</div>

<h4>Moving the marker</h4>
<p>Search for an address and press geocode. If the marker is not in the correct place, simply drag to the correct location. The Longitude and latidude for the location will update when you save.</p>

<div class="embed-responsive embed-map">
  <div id="map" class="embed-responsive-item">
  </div>
</div>

<% content_for :footer do %>
<%= javascript_include_tag '//maps.googleapis.com/maps/api/js?key=AIzaSyDkiHUkl-Syk3ZkNZYQcmLQZW3mNQZYj-Y&libraries=places&callback=initMapLocations' %>
<% end %>

app/views/locations/_location.html.erb
<div class="location-info-box clearfix locale-en" data-region="<%= location.region_en %>">
  <h4><%= location.name_en %></h4>
  <p><%= location.content_en %></p>
  <ul class="list-inline categories">
    <% if location.cat_mens %>
      <li><%=t 'mens' %></li>
    <% end %>
    <% if location.cat_womens %>
      <li><%=t 'womens' %></li>
    <% end %>
    <% if location.cat_kids %>
      <li><%=t 'kids' %></li>
    <% end %>
  </ul>

  <div class="btn data-show" data-show=".opening-hours-<%= location_counter %>" data-icon-show="fa-sort-asc" data-icon-hide="fa-sort-desc">
    <i class="fa fa-sort-desc" aria-hidden="true"></i>
  </div>

  <div class="opening-hours-<%= location_counter %> hidden">
    <%= render partial: 'locations/opening_hours', locals: { location: location } %>
  </div>

  <%= render partial: 'locations/actions', locals: { location: location, counter: location_counter } %>
</div>

<!-- Todo: Make DRY! -->
<div class="location-info-box clearfix locale-ar" data-region="<%= location.region_ar %>">
  <h4><%= location.name_ar %></h4>
  <p><%= location.content_ar %></p>

  <div class="btn data-show" data-show=".opening-hours-<%= location_counter %>" data-icon-show="fa-sort-asc" data-icon-hide="fa-sort-desc">
    <i class="fa fa-sort-desc" aria-hidden="true"></i>
  </div>

  <div class="opening-hours-<%= location_counter %> hidden">
    <%= render partial: 'locations/opening_hours', locals: { location: location } %>
  </div>

  <%= render partial: 'locations/actions', locals: { location: location, counter: location_counter } %>
</div>

app/views/locations/_opening_hours.html.erb
<strong>Opening Hours</strong>
<ul class="list-unstyled">
  <li><span><%=t 'monday' %></span> <%= location.mon %></li>
  <li><span><%=t 'tuesday' %></span> <%= location.tue %></li>
  <li><span><%=t 'wednesday' %></span> <%= location.wed %></li>
  <li><span><%=t 'thursday' %></span> <%= location.thu %></li>
  <li><span><%=t 'friday' %></span> <%= location.fri %></li>
  <li><span><%=t 'saturday' %></span> <%= location.sat %></li>
  <li><span><%=t 'sunday' %></span> <%= location.sun %></li>
</ul>

app/views/locations/edit.html.erb
<%= render partial: 'brands/brand_logo' %>

<div class="row">
  <div class="col-md-4">
    <h2><%=t :edit %> <%=t :location %></h2>
    <%= render 'form' %>
  </div>
  <div class="col-md-8">
    <%= render partial: 'google_map_geocode' %>
  </div>
</div>

app/views/locations/new.html.erb
<% content_for :brand_logo do %>
<div class="navbar-header">
  <a class="navbar-brand" href="#">
    <img alt="Brand" src='<%= @brand.logo %>' style="width: 120px;">
  </a>
</div>
<% end %>

<div class="row">
  <div class="col-md-6">
    <h2><%=t :new %> <%=t :location%></h2>
    <%= render 'form' %>
  </div>
  <div class="col-md-6">
    <%= render partial: 'google_map_geocode' %>
  </div>
</div>